services:
  ccat:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ccat_ts
    env_file:
      - .env
    environment:
      - FORCE_COLOR=1
      - QDRANT_HOST=${QDRANT_HOST:-ccat_ts_vector_memory}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
    ports:
      - ${CORE_PORT:-1865}:80
    volumes:
      - ./data:/app/data
      - ./static:/app/src/static
      - ./plugins:/app/src/plugins
    restart: unless-stopped
    depends_on:
      - vector-memory
  vector-memory:
    image: qdrant/qdrant:v1.12.0
    container_name: ccat_ts_vector_memory
    env_file:
      - .env
    environment:
      - QDRANT__LOG_LEVEL=INFO
    expose:
      - 6333
    volumes:
      - ./data/long_term_memory:/qdrant/storage
    restart: unless-stopped
