FROM oven/bun:1.2.0

WORKDIR /app

# Cache packages installation
COPY package.json bun.lock ./
COPY ./patches ./patches

RUN bun install --ignore-scripts

COPY . .

ENV NODE_ENV=development

EXPOSE 3000

CMD ["bun", "run", "dev"]