FROM oven/bun

WORKDIR /app

# Cache packages installation
COPY package.json bun.lockb ./
COPY ./patches ./patches

RUN bun install --frozen-lockfile

COPY . .

ENV NODE_ENV=development

EXPOSE 3000

CMD ["bun", "run", "dev"]