/** @type {import('typedoc').TypeDocOptions & import('typedoc-plugin-merge-modules').Config & import('typedoc-plugin-markdown').PluginOptions} */
export default {
	entryPoints: ['./src'],
	entryPointStrategy: 'expand',
	tsconfig: 'tsconfig.json',
	plugin: [
		'typedoc-vitepress-theme',
		'typedoc-plugin-markdown',
		'typedoc-plugin-merge-modules',
		'typedoc-plugin-coverage',
	],
	readme: 'none',
	indexFormat: 'table',
	parametersFormat: 'table',
	propertiesFormat: 'table',
	enumMembersFormat: 'table',
	propertyMembersFormat: 'table',
	classPropertiesFormat: 'table',
	typeDeclarationFormat: 'table',
	interfacePropertiesFormat: 'table',
	githubPages: false,
	useCodeBlocks: false,
	disableSources: true,
	excludeExternals: true,
	excludePrivate: true,
	categorizeByGroup: false,
	hidePageHeader: true,
	exclude: ['**/node_modules/**/*', '**/test/**/*', '**/*.txt'],
	out: './docs/api',
	docsRoot: './docs',
	textContentMappings: {
		'title.indexPage': 'API Reference',
		'title.memberPage': '{name}',
		'breadcrumbs.home': 'Overview',
	},
	coverageLabel: 'Coverage',
	sidebar: {
		autoConfiguration: true,
		format: 'vitepress',
		pretty: true,
		collapsed: true,
	},
}
