name: Release

env:
  HUSKY: 0

on:
  workflow_dispatch:
    inputs:
      version:
        description: Semver version
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Config GitHub
        run: |
          git config --global user.name 'Release Cat'
          git config --global user.email 'release-cat@bot.noreply.github.com'
      - name: Release
        run: bunx changelogen --release --push --${{ github.event.inputs.version }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
